#! /bin/sh

## AutoStart ##
# pgrep -x sxhkd > /dev/null || sxhkd &
if [[ $(xrandr -q | grep "HDMI-1-0 connected") ]]; then
	~/.local/bin/external-screen-right.sh
fi

~/.local/bin/autostart.sh

## Monitors ##
init_workspaces() {
	for monitor in `xrandr -q | grep " connected" | cut -d " " -f 1`; do
		bspc monitor ${monitor} -d 1 2 3 4 5 6 7 8 9 0
	done
}
init_workspaces

bspc config border_width 2
bspc config window_gap 8

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
